/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdSearch: typeof import('wot-design-uni/components/wd-search/wd-search.vue')['default']
    WdStatusTip: typeof import('wot-design-uni/components/wd-status-tip/wd-status-tip.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
