/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/index/search" |
  "/pages/message/index" |
  "/pages/order/detail" |
  "/pages/order/list" |
  "/pages/product/detail" |
  "/pages/product/favorites" |
  "/pages/publish/index" |
  "/pages/user/index" |
  "/pages/user/profile" |
  "/pages/user/settings" |
  "/pages/user/verify" |
  "/pages/order/comment/index" |
  "/pages-core/login/index" |
  "/pages-core/login/select-school";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/publish/index" | "/pages/message/index" | "/pages/user/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
